// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvW7oOAtnFBvTjYgbdVRG6DrjuBGJoiNQ',
    appId: '1:367980621544:web:d6cb1932af4f722aad235d',
    messagingSenderId: '367980621544',
    projectId: 'fixup-app-uad',
    authDomain: 'fixup-app-uad.firebaseapp.com',
    storageBucket: 'fixup-app-uad.firebasestorage.app',
    measurementId: 'G-D0LS18W2GW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_VpsarJPy3tuml3-7gLnMkjbP5Gc45Do',
    appId: '1:367980621544:android:41262476c7563baaad235d',
    messagingSenderId: '367980621544',
    projectId: 'fixup-app-uad',
    storageBucket: 'fixup-app-uad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEpsS6fONybzUor3lzQZUVCqGH5189Swk',
    appId: '1:367980621544:ios:5905e0203314f658ad235d',
    messagingSenderId: '367980621544',
    projectId: 'fixup-app-uad',
    storageBucket: 'fixup-app-uad.firebasestorage.app',
    iosBundleId: 'com.example.fixupApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEpsS6fONybzUor3lzQZUVCqGH5189Swk',
    appId: '1:367980621544:ios:5905e0203314f658ad235d',
    messagingSenderId: '367980621544',
    projectId: 'fixup-app-uad',
    storageBucket: 'fixup-app-uad.firebasestorage.app',
    iosBundleId: 'com.example.fixupApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvW7oOAtnFBvTjYgbdVRG6DrjuBGJoiNQ',
    appId: '1:367980621544:web:18f9c0142f76141cad235d',
    messagingSenderId: '367980621544',
    projectId: 'fixup-app-uad',
    authDomain: 'fixup-app-uad.firebaseapp.com',
    storageBucket: 'fixup-app-uad.firebasestorage.app',
    measurementId: 'G-21VSV2SC3H',
  );
}
